# Makefile for 1-Data_Structures
# This file is a part of 1-Data_Structures.
#
# 1-Data_Structures is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# 1-Data_Structures is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with 1-Data_Structures.  If not, see <http://www.gnu.org/licenses/>.
#
# (C) 2016, E. Higham

CC := g++
STD := -std=c++11 
CXXFLAGS = $STD 


ifdef DEBUG
CXXFLAGS += -g
OPTIM = -O0
else


all: 
$(CC) $(CXXFLAGS) $(OPTIM)


clean:

